[package]
name = "fuzzytest"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
fuzzy-matcher = "0.3.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
